{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-predictnmb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/predictNMB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/predictNMB/predictNMB_{{ version }}.tar.gz
  sha256: 154d83c3e57646e9f8de3d24fe0006c26e76d878fe82f5fcbac8e18b213a0a26

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-cutpointr
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-pmsampsize
    - r-rlang
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-assertthat
    - r-cutpointr
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-pmsampsize
    - r-rlang
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('predictNMB')"           # [not win]
    - "\"%R%\" -e \"library('predictNMB')\""  # [win]

about:
  home: https://docs.ropensci.org/predictNMB/
  license: GPL-3.0-or-later
  summary: Estimates when and where a model-guided treatment strategy may outperform a treat-all
    or treat-none approach by Monte Carlo simulation and evaluation of the Net Monetary
    Benefit. Details can be viewed in Parsons et al. (2023) <doi:10.21105/joss.05328>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
